version: "3"
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  ui:
    build: ./ui
    volumes:
      - "./ui:/app"
    ports:
      - "3006:3006"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3006
      - REACT_APP_URI=http://localhost:3000
    depends_on:
      - server
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
  schemaspy:
    image: andrewjones/schemaspy-postgres:latest
    command:
      [
        "-host",
        "db",
        "-port",
        "5432",
        "-u",
        $POSTGRES_USER,
        "-p",
        $POSTGRES_PASSWORD,
        "-db",
        $POSTGRES_DB,
        "-s",
        "public",
      ]
    volumes:
      - ./docs/schemaspy:/output
    depends_on:
      - db
