version: '3'
services:
  server:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
